### ISSUE TITLE
Compatibility with pcl 1.11

### ISSUE THREAD

**Issue by Skrsch** [rsasaki0109/ndt_omp_ros2#2]
Trying to compile with pcl 1.11 installed on my machine I get many errors like the following:

/usr/local/include/pcl-1.11/pcl/point_representation.h:263:88: error: ‘value’ is not a member of ‘pcl::traits::offset<pcl::PPFSignature, pcl::fields::alpha_m>’
make[2]: *** [CMakeFiles/ndt_omp.dir/src/pclomp/voxel_grid_covariance_omp.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/ndt_omp.dir/src/pclomp/gicp_omp.cpp.o] Error 1
make[1]: *** [CMakeFiles/ndt_omp.dir/all] Error 2
make: *** [all] Error 2

Do I really need pcl in exact version 1.8?

**Comment by rsasaki0109** [comment]
I'm sorry. I didn't notice that at all. I'm commenting because my comment might stand up to someone else's.
I recommend using the ubuntu 20.04 standard pcl, as the structure of pcl changes a lot with version up.
